### ISSUE TITLE
Map Not Orienting to Searched Location

### ISSUE THREAD

**Issue by gma00011** [WVU-CS330-2024-08-Group02/ClimaCloset#36]
Description: 

On the Weather page, there is a search bar that updates the location marked on the leaflet map. When the user enters a new location, the blue marker indicating the location switches over, but the map does not reorient itself to the searched location, and it instead stays oriented on the previous location. To look at the newly marked location, the user has to manually readjust the map. 

Steps to recreate: 
1. Open ClimaCloset main branch and type npm run dev into the terminal. 
2. Click on the Weather page
3. Type a city into the search bar that is not currently marked
4. Click search 
5. Move the map to see the newly marked location 

Submitted by: Gracie Anderson

**Comment by mp4dev** [comment]
Cameron fixed this issue. Now when a location is entered in the search bar, the map view repositions to the location.
